---
title: "survey on psmu&obi"
output: html_document
date: "2026-04-30"
---

```{r gender}
library(readxl)
survey_data <- read_excel("PSMU_OBI_cleaned.xlsx")
gender_col <- "2. Which of the following best describes your gender? /以下哪项最符合您的性别？"
gender_table <- table(survey_data[[gender_col]])
gender_percent <- round(prop.table(gender_table) * 100, 2)
gender_table
gender_percent
```
```{r age}
age_col <- "1. What is your age? /您的年龄是？"
age_table <- table(survey_data[[age_col]])
age_percent <- round(prop.table(age_table) * 100, 2)
age_table
age_percent
```

```{r}
library(dplyr)
survey_data %>%
  summarise(
    smu_mean = mean(smu_total, na.rm = TRUE),
    smu_sd = sd(smu_total, na.rm = TRUE),
    obi_mean = mean(obi_total, na.rm = TRUE),
    obi_sd = sd(obi_total, na.rm = TRUE)
  )
```



```{r}
cor_result <- cor.test(survey_data$smu_total, survey_data$obi_total, method = "spearman")

cor_result
```

```{r}
cor_result <- cor.test(survey_data$smu_total, survey_data$obi_total, method = "pearson")

cor_result
```
```{r scatterplot}
# Load package
library(ggplot2)

# Draw scatter plot
ggplot(survey_data, aes(x = smu_total, y = obi_total)) +
  geom_point(color = "skyblue", size = 2, alpha = 0.6) + 
  geom_smooth(method = "lm", color = "darkblue", se = TRUE) +  
  labs(title = "Correlation between Addictive Social Media Use and Impulsive Buying",
       x = "Problematic Social Media Use (SMU)",
       y = "Online Buying Impulsiveness (OBI)") +
  theme_minimal()
```

